apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: priv-app
  name: priv-app
  namespace: priv-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: priv-app
  template:
    metadata:
      labels:
        app: priv-app
    spec:
      imagePullSecrets:
        - name: my-key
      containers:
        - name: priv-app
          image: rexxx9865/node-k8:v1.0.1
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: priv-service
spec:
  type: NodePort
  selector:
    app: priv-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001